services:
  redis:
    image: redis:7
    container_name: mailtester-redis
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mailtester-mongo
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "27018:27017"

  spamassassin:
    image: axllent/spamassassin:latest
    container_name: mailtester-spamassassin
    restart: unless-stopped


  api:
    build: .
    container_name: mailtester-api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    ports:
      - "8000:8000"
    command: >
      uvicorn src.api.main:app
      --host 0.0.0.0
      --port 8000
      --proxy-headers
      --forwarded-allow-ips="*"

  worker:
    build: .
    container_name: mailtester-worker
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - spamassassin
    command: celery -A src.worker.celery_app.celery_app worker -l INFO -P solo

volumes:
  mongo_data:
